# Sidekiq-cron schedule for Upstox Market Data Service and Holdings Sync
# Times are in IST (configured in config/application.rb)

start_market_data:
  cron: "0 9 * * 1-5"  # 9:00 AM Monday-Friday
  class: "Upstox::StartWebsocketConnectionJob"
  queue: "market_data"
  description: "Start Upstox WebSocket market data feed at market open"

stop_market_data:
  cron: "30 15 * * 1-5"  # 3:30 PM Monday-Friday
  class: "Upstox::StopWebsocketConnectionJob"
  queue: "market_data"
  description: "Stop Upstox WebSocket market data feed at market close"

health_check_market_data:
  cron: "*/5 9-15 * * 1-5"  # Every 5 minutes from 9 AM to 3 PM, Monday-Friday
  class: "Upstox::HealthCheckWebsocketConnectionJob"
  queue: "market_data"
  description: "Health check to ensure market data service is running during trading hours"

sync_zerodha_holdings:
  cron: "0 8,16 * * 1-5"  # 8:00 AM and 4:00 PM Monday-Friday
  class: "Zerodha::SyncHoldingsJob"
  queue: "default"
  description: "Sync holdings from Zerodha for all authorized users"

sync_upstox_instrument_history:
  cron: "30 16 * * 1-5"  # 4:30 PM Monday-Friday (after market close)
  class: "Upstox::SyncInstrumentHistoryJob"
  queue: "default"
  description: "Sync daily historical candle data for all Upstox instruments"
